### ISSUE TITLE
Provide macOS build of version 2.5.0?

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/imageio-feedstock#12]
Hello, it seems there is currently no build available for macOS, although the recipe _should_ support this platform. Could you please look into this? Thanks for your help!

**Comment by almarklein** [comment]
https://anaconda.org/conda-forge/imageio/files says that you're right. I have no idea TBH.

**Comment by hoechenberger** [comment]
It seems the build / test failed on macOS:
https://travis-ci.org/conda-forge/imageio-feedstock/builds/489760974?utm_source=github_status&utm_medium=notification

Hence the package was not uploaded.

**Comment by djhoese** [comment]
@hoechenberger Can't you rerun the travis job to get it to rebuild? It looks like it was just some .so issue that is likely fixed by now.

**Comment by almarklein** [comment]
Good one! I just restarted the failing build. Let's see...

**Comment by djhoese** [comment]
Success! https://anaconda.org/conda-forge/imageio/files

**Comment by hoechenberger** [comment]
Cool, thank you!!

**Comment by almarklein** [comment]
@hoechenberger thanks for the heads-up!
