### ISSUE TITLE
Re-run CI to fix build error

### ISSUE THREAD

**Issue by lschr** [conda-forge/imageio-feedstock#75]
### Comment:

AFAICS the current build failure was caused by a problem downloading the test file. It should be fixed by re-running the CI.

**Comment by anjos** [comment]
I so did - but that does not seem to fix it.  Network errors are still there.  Will retry later.

**Comment by anjos** [comment]
Still not working.  If you have any other suggestions, @lschr - please let me know.

**Comment by lschr** [comment]
I have no idea… It works locally for me and it worked for PR #74… Maybe patch to skip the test?

**Comment by lschr** [comment]
Fixed by #78.
